Traceback (most recent call last):
  File "/Users/harsh/code/dpvcg/dpv/documentation-generator/./verify_002.py", line 30, in <module>
    raise Exception('declare SHACLROOT to path containing shaclvalidate.sh')
Exception: declare SHACLROOT to path containing shaclvalidate.sh
